"""Accessible standalone reviewer UI for the accepted blinded packet."""

ANNOTATION_WEB_HTML = r'''<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Horizon — независимая оценка кандидатов</title><style>
:root{--ink:#15243b;--blue:#215fb5;--line:#d8e1ee;--warn:#815600;--good:#176b45}*{box-sizing:border-box}body{margin:0;background:#f5f7fa;color:var(--ink);font:15px/1.5 Arial,sans-serif}header{background:linear-gradient(120deg,#10294c,#2468b7);color:#fff;padding:28px max(20px,calc((100% - 980px)/2))}header h1{margin:0 0 5px;font-size:26px}header p{margin:0;opacity:.88}main{max-width:980px;margin:22px auto;padding:0 18px 60px}section,article{background:#fff;border:1px solid var(--line);border-radius:12px;padding:18px;margin:12px 0}.note{background:#fff7df;color:var(--warn);padding:11px 13px;border-radius:8px}.ok{background:#eaf8f1;color:var(--good);padding:11px 13px;border-radius:8px}label{display:block;font-weight:bold;color:#445a74;margin:10px 0}input,select,textarea{display:block;width:100%;margin-top:5px;padding:10px;border:1px solid #b9c8db;border-radius:7px;font:inherit}textarea{min-height:90px;resize:vertical}button{border:0;border-radius:8px;background:var(--blue);color:#fff;font-weight:bold;padding:12px 18px;cursor:pointer}button:disabled{opacity:.55}a{color:var(--blue)}table{border-collapse:collapse;width:100%;font-size:13px}th,td{border-bottom:1px solid var(--line);padding:7px;text-align:left}.questions{display:grid;grid-template-columns:1fr 1fr;gap:10px}.meta{color:#667b93;font-size:13px}.checks label{font-weight:normal}.checks input{display:inline;width:auto;margin-right:8px}@media(max-width:700px){.questions{grid-template-columns:1fr}}
</style></head><body><header><h1>Независимая оценка публикационных кандидатов</h1><p>Ослеплённый development-пакет Horizon · статус и балл системы скрыты</p></header>
<main><section><p><a href="/">← Вернуться в Horizon</a></p><div class="note">Это не голосование о рыночном успехе. Оценивайте только публикационные основания на указанную дату. Если данных недостаточно, выбирайте «неясно» или «невозможно оценить». Заполняйте анкету самостоятельно и не открывайте закрытый ключ.</div><label>Идентификатор рецензента<input id="reviewer" maxlength="120" required placeholder="Имя или согласованный код"></label><div class="checks"><label><input type="checkbox" id="independent">Я заполнял(а) анкету независимо от другого рецензента</label><label><input type="checkbox" id="blind">Мне не показывали статус, score и gates системы</label><label><input type="checkbox" id="persist">После проверки сохранить полную анкету в неизменяемой локальной истории Horizon</label></div><p id="summary">Загрузка закреплённого пакета…</p></section><form id="review"><div id="items"></div><section><button id="validate" type="submit">Проверить и скачать анкету</button><p id="result" aria-live="polite"></p></section></form></main>
<script>
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const labels={yes:'Да',no:'Нет',uncertain:'Неясно',not_assessable:'Невозможно оценить'};let packet=null;
const download=(value,name)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
function seriesTable(points){return `<details><summary>Публикационный ряд в закреплённом корпусе</summary><div style="overflow:auto"><table><thead><tr><th>Окно</th><th>Работ темы / корпуса</th><th>Доля</th><th>Покрытие</th></tr></thead><tbody>${points.map(p=>`<tr><td>${esc(p.start)} — ${esc(p.end)}</td><td>${p.topic_works} / ${p.corpus_works??'неизвестно'}</td><td>${p.share==null?'неизвестно':(p.share*100).toFixed(3)+'%'}</td><td>${p.coverage_comparable===true?'сопоставимо':p.coverage_comparable===false?'несопоставимо':'неизвестно'}</td></tr>`).join('')}</tbody></table></div></details>`}
function renderItem(item,index){const questions=Object.entries(item.questions).map(([name,q])=>`<label>${esc(q.meaning)}<select data-axis="${esc(name)}" required><option value="">Выберите ответ</option>${q.choices.map(v=>`<option value="${esc(v)}">${esc(labels[v]||v)}</option>`).join('')}</select></label>`).join('');const works=item.works.map(w=>`<li>${esc(w.published_at)} · ${esc(w.title)} · ${w.sources.map((s,i)=>`<a href="${esc(s)}" target="_blank" rel="noopener">источник ${i+1}</a>`).join(' · ')}</li>`).join('');const sample=item.works_truncated?`Показана временная выборка ${item.works_shown} из ${item.composition_work_count} публикаций; полный состав скрыт вместе с техническим ключом.`:`Показаны все ${item.composition_work_count} публикаций состава.`;return `<article data-item="${esc(item.item_id)}"><h2>${index+1}. ${esc(item.generated_label)}</h2><p class="meta">Срез: строго раньше ${esc(item.as_of_date)}. Внутренний номер: ${esc(item.item_id)}.</p><p class="meta">${esc(sample)}</p><ol>${works}</ol>${seriesTable(item.publication_series)}<div class="questions">${questions}</div><label>Объяснение решения<textarea data-role="rationale" minlength="20" maxlength="5000" required></textarea></label><label>Дополнительные HTTPS-источники, по одному на строку<textarea data-role="sources"></textarea></label></article>`}
async function load(){try{const r=await fetch('/annotation/current');const p=await r.json();if(!r.ok)throw new Error(p.detail||'Пакет не прочитан');packet=p;document.getElementById('summary').textContent=`Пакет ${p.package_id}. Позиций: ${p.items.length}. SHA: ${p.packet_payload_sha256}. Gold labels отсутствуют.`;document.getElementById('items').innerHTML=p.items.map(renderItem).join('')}catch(e){document.getElementById('summary').textContent=e.message;document.getElementById('validate').disabled=true}}
document.getElementById('review').addEventListener('submit',async event=>{event.preventDefault();const button=document.getElementById('validate'),result=document.getElementById('result');button.disabled=true;try{if(!packet)throw new Error('Пакет ещё не загружен');const annotations=Array.from(document.querySelectorAll('article[data-item]')).map(article=>({item_id:article.dataset.item,answers:Object.fromEntries(Array.from(article.querySelectorAll('select[data-axis]')).map(select=>[select.dataset.axis,select.value])),rationale:article.querySelector('[data-role="rationale"]').value,sources:article.querySelector('[data-role="sources"]').value.split('\n').map(v=>v.trim()).filter(Boolean)}));const submission={version:'independent-annotation-submission-0.4.21',package_id:packet.package_id,packet_payload_sha256:packet.packet_payload_sha256,reviewer_id:document.getElementById('reviewer').value,independent_review_declared:document.getElementById('independent').checked,system_status_not_seen_declared:document.getElementById('blind').checked,annotations};const persist=document.getElementById('persist').checked;const endpoint=persist?'/annotation/current/submissions':'/annotation/current/validate';const body=persist?{submission,operation_id:crypto.randomUUID()}:submission;const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const response=await r.json();if(!r.ok)throw new Error(response.detail||'Анкета не прошла проверку');const checked=response.validated_submission||response;download(checked,`saia-review-${checked.reviewer_id.replace(/[^a-zA-Z0-9_-]+/g,'_')}.validated.json`);result.className='ok';result.textContent=persist?`Анкета сохранена append-only как ${response.submission_id} и скачана. SHA: ${checked.submission_payload_sha256}. Это отдельное мнение, не gold и не изменение статуса.`:`Анкета проверена и скачана. SHA: ${checked.submission_payload_sha256}. Это отдельное мнение, не gold и не изменение статуса.`}catch(e){result.className='note';result.textContent=e.message}finally{button.disabled=false}});load();
</script></body></html>'''
