"""Non-technical UI for explicit retrieval adjudication and pipeline handoff."""

RETRIEVAL_ADJUDICATION_HTML = r'''<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Horizon — арбитраж релевантности</title><style>
:root{--ink:#13263e;--blue:#205eaa;--line:#d6e0ec;--warn:#765000;--good:#176b45}*{box-sizing:border-box}body{margin:0;background:#f4f7fa;color:var(--ink);font:15px/1.5 Arial,sans-serif}header{background:linear-gradient(120deg,#10294c,#2468b7);color:#fff;padding:28px max(20px,calc((100% - 1050px)/2))}header h1{margin:0 0 5px}main{max-width:1050px;margin:22px auto;padding:0 18px 60px}section,article{background:#fff;border:1px solid var(--line);border-radius:12px;padding:18px;margin:12px 0}.note{background:#fff7df;color:var(--warn);padding:11px 13px;border-radius:8px}.ok{background:#eaf8f1;color:var(--good);padding:11px 13px;border-radius:8px}label{display:block;font-weight:bold;color:#445a74;margin:10px 0}input,select,textarea{display:block;width:100%;margin-top:5px;padding:10px;border:1px solid #b9c8db;border-radius:7px;font:inherit}textarea{min-height:75px}button{border:0;border-radius:8px;background:var(--blue);color:#fff;font-weight:bold;padding:12px 18px;cursor:pointer}button:disabled{opacity:.55}.grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.meta{color:#637991;font-size:13px}.checks label{font-weight:normal}.checks input{display:inline;width:auto;margin-right:8px}a{color:var(--blue)}@media(max-width:720px){.grid{grid-template-columns:1fr}}
</style></head><body><header><h1>Необязательный арбитраж релевантности</h1><p>Сопоставление двух независимых оценок качества поиска</p></header><main>
<section><p><a href="/">← Вернуться в Horizon</a></p><div class="note">Этот контур необязателен: система формирует кандидатов слабых сигналов и без него. Здесь оценивается только качество входной выдачи; арбитраж не подтверждает слабый сигнал и не меняет научные пороги.</div><p id="status">Загрузка…</p><div class="grid"><label>Первая анкета<select id="left"></select></label><label>Вторая анкета<select id="right"></select></label></div><label>Идентификатор арбитра<input id="adjudicator" maxlength="120" placeholder="Имя или согласованный код"></label><button id="open" type="button">Открыть две анкеты</button></section>
<form id="decision"><div id="items"></div><section><button id="save" type="submit" disabled>Сохранить решение арбитра</button><p id="result"></p></section></form>
<script>
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const jobId=new URLSearchParams(location.search).get('job_id');let packet=null,left=null,right=null,adjudicationId=null;const base=jobId?`/jobs/${encodeURIComponent(jobId)}/retrieval-review`:null;
async function json(url,options){const r=await fetch(url,options),p=await r.json();if(!r.ok)throw new Error(p.detail||JSON.stringify(p));return p}
function option(row){return `<option value="${esc(row.submission_id)}">${esc(row.reviewer_id)} · ${esc(row.created_at)}</option>`}
async function load(){try{if(!jobId)throw new Error('В адресе отсутствует job_id. Откройте страницу из завершённой задачи.');const [p,h,s]=await Promise.all([json(base),json(`${base}/submissions`),json(`${base}/status`)]);packet=p;document.getElementById('status').textContent=`Состояние: ${s.state}. Анкет: ${h.total}; арбитражей: ${s.stored_adjudications}.`;const opts='<option value="">Выберите анкету</option>'+h.submissions.map(option).join('');leftEl().innerHTML=opts;rightEl().innerHTML=opts;if(h.total<2)document.getElementById('open').disabled=true}catch(e){document.getElementById('status').textContent=e.message;document.getElementById('open').disabled=true}}
const leftEl=()=>document.getElementById('left'),rightEl=()=>document.getElementById('right');
function render(){const a=Object.fromEntries(left.validated_submission.annotations.map(x=>[x.item_id,x])),b=Object.fromEntries(right.validated_submission.annotations.map(x=>[x.item_id,x]));document.getElementById('items').innerHTML=packet.items.map((item,i)=>`<article data-item="${esc(item.item_id)}"><h3>${i+1}. ${esc(item.document.title)}</h3><p><b>Целевая тема:</b> ${esc(item.target_topic)}</p><div class="grid"><p><b>${esc(left.reviewer_id)}:</b> ${esc(a[item.item_id].answers.topical_relevance)} / ${esc(a[item.item_id].answers.evidence_role)}<br>${esc(a[item.item_id].rationale)}</p><p><b>${esc(right.reviewer_id)}:</b> ${esc(b[item.item_id].answers.topical_relevance)} / ${esc(b[item.item_id].answers.evidence_role)}<br>${esc(b[item.item_id].rationale)}</p></div><label>Итоговая релевантность<select data-role="label" required><option value="">Выберите</option><option value="relevant">Релевантно</option><option value="not_relevant">Не релевантно</option></select></label><label>Объяснение арбитра<textarea data-role="rationale" minlength="20" maxlength="5000" required></textarea></label></article>`).join('');document.getElementById('save').disabled=false}
document.getElementById('open').onclick=async()=>{try{if(!leftEl().value||!rightEl().value||leftEl().value===rightEl().value)throw new Error('Выберите две разные анкеты.');[left,right]=await Promise.all([json(`${base}/submissions/${encodeURIComponent(leftEl().value)}`),json(`${base}/submissions/${encodeURIComponent(rightEl().value)}`)]);render()}catch(e){document.getElementById('result').className='note';document.getElementById('result').textContent=e.message}};
document.getElementById('decision').onsubmit=async e=>{e.preventDefault();const out=document.getElementById('result');try{const decisions=[...document.querySelectorAll('article[data-item]')].map(x=>({item_id:x.dataset.item,topical_relevance:x.querySelector('[data-role="label"]').value,rationale:x.querySelector('[data-role="rationale"]').value,sources:[]}));const body={left_submission_id:left.submission_id,right_submission_id:right.submission_id,adjudicator_id:document.getElementById('adjudicator').value,decisions,operation_id:crypto.randomUUID()};const saved=await json(`${base}/adjudications`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});adjudicationId=saved.adjudication_id;const m=saved.adjudication.metrics;out.className='ok';out.textContent=`Решение сохранено. Релевантно ${m.relevant} из ${m.assignments}; точность этой выдачи ${(100*m.precision_on_returned_assignments).toFixed(1)}%. Это не точность слабых сигналов и не условие их показа.`;}catch(err){out.className='note';out.textContent=err.message}};load();
</script></main></body></html>'''
