"""Standalone UI for blinded review of frozen retrieval assignments."""

RETRIEVAL_REVIEW_HTML = r'''<!doctype html>
<html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Horizon — проверка релевантности поиска</title><style>
:root{--ink:#13263e;--blue:#205eaa;--line:#d6e0ec;--warn:#765000;--good:#176b45}*{box-sizing:border-box}body{margin:0;background:#f4f7fa;color:var(--ink);font:15px/1.5 Arial,sans-serif}header{background:linear-gradient(120deg,#10294c,#2468b7);color:white;padding:28px max(20px,calc((100% - 980px)/2))}header h1{margin:0 0 5px;font-size:26px}header p{margin:0;opacity:.88}main{max-width:980px;margin:22px auto;padding:0 18px 60px}section,article{background:white;border:1px solid var(--line);border-radius:12px;padding:18px;margin:12px 0}.note{background:#fff7df;color:var(--warn);padding:11px 13px;border-radius:8px}.ok{background:#eaf8f1;color:var(--good);padding:11px 13px;border-radius:8px}label{display:block;font-weight:bold;color:#445a74;margin:10px 0}input,select,textarea{display:block;width:100%;margin-top:5px;padding:10px;border:1px solid #b9c8db;border-radius:7px;font:inherit}textarea{min-height:80px;resize:vertical}button{border:0;border-radius:8px;background:var(--blue);color:white;font-weight:bold;padding:12px 18px;cursor:pointer}button:disabled{opacity:.55}a{color:var(--blue)}.questions{display:grid;grid-template-columns:1fr 1fr;gap:10px}.meta{color:#637991;font-size:13px}.checks label{font-weight:normal}.checks input{display:inline;width:auto;margin-right:8px}.topic{font-size:14px;color:#536b85}.document-title{font-size:18px;margin:5px 0}@media(max-width:700px){.questions{grid-template-columns:1fr}}
</style></head><body><header><h1>Проверка релевантности поиска</h1><p>Проверка расширенного поиска и новых многоветочных выдач · отдельно от оценки слабых сигналов</p></header><main>
<section><p><a href="/">← Вернуться в Horizon</a></p><div class="note">Оценивайте только соответствие статьи указанной теме. Не оценивайте рынок, будущий успех или статус слабого сигнала. Исходный порядок выдачи и внутренние счётчики скрыты.</div><label>Идентификатор рецензента<input id="reviewer" maxlength="120" required placeholder="Имя или согласованный код"></label><div class="checks"><label><input type="checkbox" id="independent">Я заполнял(а) анкету независимо</label><label><input type="checkbox" id="blind">Мне не показывали скрытые счётчики и исходный порядок выдачи</label><label><input type="checkbox" id="persist">После проверки сохранить полную анкету в неизменяемой локальной истории Horizon</label></div><p id="summary">Загрузка закреплённого пакета…</p></section>
<form id="review"><div id="items"></div><section><button id="validate" type="submit">Проверить и скачать анкету</button><p id="result" aria-live="polite"></p></section></form></main>
<script>
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const labels={relevant:'Относится к теме',not_relevant:'Не относится',uncertain:'Неясно',central:'Центральная тема',supporting:'Поддерживающий метод',incidental:'Случайное упоминание'};let packet=null;const jobId=new URLSearchParams(location.search).get('job_id');const reviewBase=jobId?`/jobs/${encodeURIComponent(jobId)}/retrieval-review`:'/retrieval-review/current';
const download=(value,name)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
function itemHtml(item,index){const d=item.document,categories=(d.categories||[]).join(', '),abstract=d.abstract?`<p>${esc(d.abstract)}</p>`:'<p class="meta">Аннотация в источнике не получена.</p>',link=d.url?` · <a href="${esc(d.url)}" target="_blank" rel="noopener">открыть первоисточник</a>`:'';const questions=Object.entries(item.questions).map(([name,q])=>`<label>${esc(q.meaning)}<select data-axis="${esc(name)}" required><option value="">Выберите ответ</option>${q.choices.map(v=>`<option value="${esc(v)}">${esc(labels[v]||v)}</option>`).join('')}</select></label>`).join('');return `<article data-item="${esc(item.item_id)}"><p class="topic">Целевая тема: <strong>${esc(item.target_topic)}</strong></p><h2 class="document-title">${index+1}. ${esc(d.title)}</h2><p class="meta">Первое размещение: ${esc(d.first_submission_date)}${categories?` · категории: ${esc(categories)}`:''}${link}</p>${abstract}<div class="questions">${questions}</div><label>Объяснение решения<textarea data-role="rationale" minlength="20" maxlength="5000" required></textarea></label><label>Дополнительные HTTPS-источники, по одному на строку<textarea data-role="sources"></textarea></label></article>`}
async function load(){try{const r=jobId?await fetch(reviewBase):await fetch('/retrieval-review/current');const p=await r.json();if(!r.ok)throw new Error(p.detail||'Пакет не прочитан');packet=p;document.getElementById('summary').textContent=`Пакет ${p.package_id}. Назначений: ${p.items.length}. SHA: ${p.packet_payload_sha256}. Gold labels отсутствуют.${jobId?` Задача: ${jobId}.`:''}`;document.getElementById('items').innerHTML=p.items.map(itemHtml).join('')}catch(e){document.getElementById('summary').textContent=e.message;document.getElementById('validate').disabled=true}}
document.getElementById('review').addEventListener('submit',async event=>{event.preventDefault();const button=document.getElementById('validate'),result=document.getElementById('result');button.disabled=true;try{if(!packet)throw new Error('Пакет ещё не загружен');const annotations=Array.from(document.querySelectorAll('article[data-item]')).map(article=>({item_id:article.dataset.item,answers:Object.fromEntries(Array.from(article.querySelectorAll('select[data-axis]')).map(select=>[select.dataset.axis,select.value])),rationale:article.querySelector('[data-role="rationale"]').value,sources:article.querySelector('[data-role="sources"]').value.split('\n').map(v=>v.trim()).filter(Boolean)}));const submission={version:'retrieval-relevance-review-submission-0.4.26',package_id:packet.package_id,packet_payload_sha256:packet.packet_payload_sha256,reviewer_id:document.getElementById('reviewer').value,independent_review_declared:document.getElementById('independent').checked,hidden_fields_not_seen_declared:document.getElementById('blind').checked,annotations};const persist=document.getElementById('persist').checked;const endpoint=jobId?(persist?`${reviewBase}/submissions`:`${reviewBase}/validate`):(persist?'/retrieval-review/current/submissions':'/retrieval-review/current/validate');const body=persist?{submission,operation_id:crypto.randomUUID()}:submission;const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const response=await r.json();if(!r.ok)throw new Error(response.detail||'Анкета не прошла проверку');const checked=response.validated_submission||response;download(checked,`saia-retrieval-review-${checked.reviewer_id.replace(/[^a-zA-Z0-9_-]+/g,'_')}.validated.json`);result.className='ok';result.textContent=persist?`Анкета сохранена append-only как ${response.submission_id} и скачана. SHA: ${checked.submission_payload_sha256}. Это отдельное мнение, не precision или gold.`:`Анкета проверена и скачана. SHA: ${checked.submission_payload_sha256}. Это отдельное мнение, не precision, gold или изменение production.`}catch(e){result.className='note';result.textContent=e.message}finally{button.disabled=false}});load();
</script></body></html>'''
