"""Optional PESTLE/industry notebook; author hypotheses, not generated truth."""

ANALYSIS_STYLE = r'''
.impact-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.impact-section{border:1px solid var(--line);border-radius:10px;margin:9px 0;padding:11px}.impact-section>summary{cursor:pointer;font-size:13px;font-weight:700;color:var(--blue-dark)}.impact-section label{display:block;margin:10px 0 0;font-size:12px;color:var(--muted)}.impact-section .field{width:100%;margin-top:5px;min-width:0}.impact-section textarea{min-height:80px;resize:vertical}#analysis-form .field{font-size:13px;font-weight:400}.impact-refs{max-height:170px;overflow:auto;margin-top:8px}.impact-refs label{display:flex;gap:8px;align-items:flex-start;font-size:11px;font-weight:400;line-height:1.4}.impact-refs input{margin-top:3px;flex:none}.impact-help{margin:8px 0;color:var(--muted);font-size:12px;line-height:1.5}.impact-toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:12px 0}.drawer .block{scroll-margin-top:80px}@media(max-width:600px){.impact-grid{grid-template-columns:1fr}}
'''

ANALYSIS_SCRIPT = r'''
const impactDimensions={political:['Политика и государственные приоритеты','Какие государственные приоритеты или ограничения могут повлиять на развитие?'],economic:['Экономика и рынок','Какие затраты, рынки или бизнес-процессы могут измениться?'],social:['Общество и люди','Какие навыки, поведение или вопросы принятия технологии могут измениться?'],technological:['Технологии','Что станет возможным и какие технические зависимости остаются?'],legal:['Право и регулирование','Какие разрешения, стандарты или правовые ограничения нужно проверить?'],environmental:['Экология','Как может измениться использование энергии, материалов или отходов?']};
const impactEffects={unknown:'Не определено',opportunity:'Возможность',risk:'Риск',mixed:'Возможности и риски'},impactHorizons={not_assessed:'Срок не оценён','0_2_years':'До 2 лет','3_5_years':'3–5 лет',over_5_years:'Более 5 лет'};
function analysisControls(){return `<details class="block compact-details" id="card-analysis"><summary>PESTLE и влияние на отрасли <a class="help-context" href="/help#pestle" data-horizon-help="pestle" aria-label="Как работать с PESTLE и влиянием на отрасли">?</a></summary><p class="impact-help">Возможные последствия, которые описывает скаут. Они не меняют рейтинг и не являются экспертной валидацией.</p><div id="analysis-content" class="empty">Откройте раздел, чтобы посмотреть или подготовить заметку.</div></details>`}
function impactOptions(items,selected){return Object.entries(items).map(([id,label])=>`<option value="${id}"${id===selected?' selected':''}>${label}</option>`).join('')}
function impactReferenceList(refs,selected=[]){return `<details><summary class="impact-help">Основания (${selected.length})</summary><div class="impact-refs">${refs.length?refs.map(r=>`<label><input type="checkbox" data-impact-reference value="${esc(r.id)}"${selected.includes(r.id)?' checked':''}><span>${esc(r.title)}<br><a href="${esc(url(r.url)||'#')}" target="_blank" rel="noopener noreferrer">Источник</a> · ${fmtDate(r.date)}</span></label>`).join(''):'<p class="impact-help">Сохранённых оснований пока нет. Можно записать гипотезу без источников; она будет так отмечена.</p>'}</div></details>`}
function impactRow(type,key,row,refs){const data=row||{},name=type==='pestle'?impactDimensions[key][0]:'Отрасль',hint=type==='pestle'?impactDimensions[key][1]:'Опишите механизм влияния на отрасль, а не только название технологии.';return `<details class="impact-section" data-impact-row="${type}" data-impact-dimension="${esc(key||'')}"><summary>${esc(data.industry||name)}${row?' · заполнено':''}</summary>${type==='industry'?`<label>Отрасль или сфера<input class="field" data-impact-field="industry" maxlength="120" value="${esc(data.industry||'')}" placeholder="Например, логистика"></label>`:''}<label>Гипотеза<textarea class="field" data-impact-field="text" maxlength="1800" placeholder="${esc(hint)}">${esc(data.text||'')}</textarea></label><div class="impact-grid"><label>Характер влияния<select class="field" data-impact-field="effect">${impactOptions(impactEffects,data.effect||'unknown')}</select></label><label>Ожидаемый горизонт<select class="field" data-impact-field="horizon">${impactOptions(impactHorizons,data.horizon||'not_assessed')}</select></label></div><label>Условия реализации<textarea class="field" data-impact-field="dependencies" maxlength="800" placeholder="Что должно произойти, чтобы гипотеза реализовалась?">${esc(data.dependencies||'')}</textarea></label>${impactReferenceList(refs,data.evidence_ids)}${type==='industry'?'<button type="button" class="button ghost small" data-impact-remove style="margin-top:10px">Убрать из заметки</button>':''}</details>`}
async function loadAnalysis(c){const mission=state.mission,score=state.score,box=$('analysis-content');if(!box)return;const current=()=>state.current?.candidate_id===c.candidate_id&&state.mission===mission&&state.score===score&&$('analysis-content')===box;box.textContent='Загружаю заметку…';try{const prefix=`/signals/${encodeURIComponent(mission)}/${c.candidate_id}`,params=`?score_run_id=${score}`;const [packet,catalog]=await Promise.all([request(prefix+'/analysis-note'+params),request(prefix+'/analysis-references'+params)]);if(!current())return;if(packet.binding.composition_sha256!==c.composition_sha256||catalog.binding.composition_sha256!==c.composition_sha256)throw Error('Analysis composition mismatch');const note=packet.note,content=note?.content||{},refs=[...new Map([...(catalog.references||[]),...(content.references||[])].map(r=>[r.id,r])).values()];box.classList.remove('empty');box.dataset.loaded='true';box.innerHTML=`<p class="impact-help" id="analysis-version">${note?`Сохранена версия ${note.revision} · ${fmtDate(note.created_at)}`:'Заметка ещё не подготовлена.'} История сохранений не удаляется.</p><form id="analysis-form" class="form-grid"><label>Автор<input class="field" id="analysis-author" maxlength="120" required value="${esc(content.author||'Технологический скаут')}"></label><p class="impact-help">Имя указано автором; система не подтверждает личность или квалификацию.</p><h3 style="margin-top:10px">PESTLE</h3>${Object.keys(impactDimensions).map(key=>impactRow('pestle',key,(content.pestle||[]).find(r=>r.dimension===key),refs)).join('')}<h3 style="margin-top:15px">Влияние на отрасли и сферы</h3><div id="impact-industries">${(content.industry_impacts||[]).map(row=>impactRow('industry','',row,refs)).join('')}</div><button class="button ghost small" type="button" id="impact-add">Добавить отрасль</button><label>Вывод скаута<textarea class="field" id="analysis-summary" maxlength="1800" placeholder="Что стоит исследовать дальше и почему?">${esc(content.summary||'')}</textarea></label><p class="impact-help">Ссылка подтверждает наличие материала, но не доказывает гипотезу. Без источников гипотеза будет отмечена отдельно.</p><button class="button light small" id="analysis-save" type="submit">Сохранить заметку</button><p id="analysis-message" role="status" class="impact-help"></p></form>`;
let revision=packet.revision,operation=crypto.randomUUID(),sentContent=null;
$('impact-add').onclick=()=>{if($('impact-industries').querySelectorAll('[data-impact-row]').length>=8){$('analysis-message').textContent='В одной заметке можно описать до восьми отраслей.';return}$('impact-industries').insertAdjacentHTML('beforeend',impactRow('industry','',null,refs));$('impact-industries').lastElementChild.open=true};
box.addEventListener('click',e=>{const remove=e.target.closest('[data-impact-remove]');if(remove)remove.closest('[data-impact-row]').remove()});
$('analysis-form').onsubmit=async e=>{e.preventDefault();const message=$('analysis-message'),form=e.currentTarget;let body;try{body={author:$('analysis-author').value.trim(),summary:$('analysis-summary').value.trim(),pestle:[],industry_impacts:[]};for(const el of form.querySelectorAll('[data-impact-row]')){const value=name=>el.querySelector(`[data-impact-field="${name}"]`)?.value.trim()||'',text=value('text'),dependencies=value('dependencies'),industry=value('industry'),ids=[...el.querySelectorAll('[data-impact-reference]:checked')].map(x=>x.value);if(!text&&!dependencies&&!industry&&!ids.length)continue;if(text.length<10)throw Error('Опишите каждую заполненную гипотезу — не менее 10 символов.');if(ids.length>6)throw Error('Для одной гипотезы выберите не более шести оснований.');const row={text,dependencies,effect:value('effect'),horizon:value('horizon'),evidence_ids:ids};if(el.dataset.impactRow==='pestle'){row.dimension=el.dataset.impactDimension;body.pestle.push(row)}else{if(industry.length<2)throw Error('Укажите отрасль или сферу.');row.industry=industry;body.industry_impacts.push(row)}}if(!body.summary&&!body.pestle.length&&!body.industry_impacts.length)throw Error('Добавьте хотя бы одну гипотезу или вывод.');if(sentContent!==JSON.stringify(body)){operation=crypto.randomUUID();sentContent=JSON.stringify(body)}const controls=[...form.querySelectorAll('input,textarea,select,button')];controls.forEach(x=>x.disabled=true);message.textContent='Сохраняю…';try{const saved=await post(prefix+'/analysis-note'+params,{...body,expected_revision:revision,operation_id:operation});if(!current())return;revision=saved.note.revision;$('analysis-version').textContent=`Сохранена версия ${revision} · ${fmtDate(saved.note.created_at)}. История сохранений не удаляется.`;message.textContent='Заметка сохранена как гипотезы скаута. Научная оценка не изменена.';operation=crypto.randomUUID();sentContent=null}finally{if(current())controls.forEach(x=>x.disabled=false)}}catch(error){if(current())message.textContent=error.message||'Не удалось сохранить заметку. Текст остаётся в форме.'}};
}catch(error){if(current()){box.classList.add('empty');box.textContent='Не удалось загрузить заметку. Исходная карточка остаётся доступной.'}console.error('Analysis note unavailable',error)}}
function setupAnalysis(c){const details=$('card-analysis'),box=$('analysis-content');details.ontoggle=()=>{if(details.open&&details.isConnected&&!box.dataset.loaded)loadAnalysis(c)};$('open-card-analysis').onclick=e=>{e.preventDefault();details.open=true;details.scrollIntoView({behavior:'smooth',block:'start'})};const anchor=$('download-card');anchor.href=`/signals/${encodeURIComponent(state.mission)}/${c.candidate_id}/brief?score_run_id=${state.score}`}
'''
